services:
  # Backend Service
  - type: web
    name: hirex-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: export PYTHONPATH=$PYTHONPATH:./src && uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHONPATH
        value: ./src
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: REMOTE_STORAGE_PROVIDER
        value: r2
      - key: OPENAI_API_KEY
        sync: false
      - key: R2_ACCESS_KEY_ID
        sync: false
      - key: R2_SECRET_ACCESS_KEY
        sync: false
      - key: R2_BUCKET_NAME
        sync: false
      - key: R2_ENDPOINT_URL
        sync: false
      - key: MODEL
        value: gpt-4o-mini

  # Frontend Static Site
  - type: web
    name: HireX
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
